### ISSUE TITLE
SSL certification problem

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#1]
```
Joshuas-Air:Web-stuff jovo$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6121    0  6121    0     0   7103      0 --:--:-- --:--:-- --:--:-- 16543
Downloading Meteor distribution

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Installation failed.
Joshuas-Air:Web-stuff jovo$ 
```

-k/--insecure didn't fix

**Comment by j6k4m8** [comment]
Interesting. Haven't seen that before. I'll look into it tomorrow, but in
the meantime https://github.com/meteor/meteor#slow-start-for-developers may
help with a manual install.

**Comment by jovo** [comment]
fail :(

On Mon, Aug 17, 2015 at 11:48 PM, Jordan Matelsky notifications@github.com
wrote:

> Interesting. Haven't seen that before. I'll look into it tomorrow, but in
> the meantime https://github.com/meteor/meteor#slow-start-for-developers
> may
> help with a manual install.
> 
> On Mon, Aug 17, 2015 at 11:35 PM joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > Joshuas-Air:Web-stuff jovo$ curl https://install.meteor.com/ | sh
> > % Total % Received % Xferd Average Speed Time Time Time Current
> > Dload Upload Total Spent Left Speed
> > 100 6121 0 6121 0 0 7103 0 --:--:-- --:--:-- --:--:-- 16543
> > Downloading Meteor distribution
> > 
> > curl: (60) SSL certificate problem: unable to get local issuer
> > certificate
> > More details here: http://curl.haxx.se/docs/sslcerts.html
> > 
> > curl performs SSL certificate verification by default, using a "bundle"
> > of Certificate Authority (CA) public keys (CA certs). If the default
> > bundle file isn't adequate, you can specify an alternate file
> > using the --cacert option.
> > If this HTTPS server uses a certificate signed by a CA represented in
> > the bundle, the certificate verification probably failed due to a
> > problem with the certificate (it might be expired, or the name might
> > not match the domain name in the URL).
> > If you'd like to turn off curl's verification of the certificate, use
> > the -k (or --insecure) option.
> > Installation failed.
> > Joshuas-Air:Web-stuff jovo$
> > 
> > -k/--insecure didn't fix
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openconnectome/ocp.me/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/1#issuecomment-132063617
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
Your other (untested) alternative is to go to that page and try downloading
the script itself, and then just run it locally

**Comment by gkiar** [comment]
strange.... @j6k4m8, the script worked for me except you should replace:

`git@github.com/openconnectome/ocp.me ocp.me`
with
`git@github.com:openconnectome/ocp.me ocp.me`

## 

Greg Kiar gkiar07@gmail.com

**Comment by j6k4m8** [comment]
Changed in the readme. Good call!
