### ISSUE TITLE
update graph explorer url

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ocp.me#100]
@jovo @j6k4m8 

128.220.176.8/Graph-Explorer/shiny/

**Comment by jovo** [comment]
i update repo.  i can't roll because i don't have log in credentials nor do i know which url to ssh into.

@alexbaden

**Comment by alexbaden** [comment]
@j6k4m8

**Comment by jovo** [comment]
@j6k4m8 this is you again, for some reason :-)

**Comment by alexbaden** [comment]
I don't know how to do it. We should maybe document it internally?

**Comment by jovo** [comment]
done.
