### ISSUE TITLE
vx.neurodata.io currently links to: http://shiny.neurodata.io/data-analytics-website/Code/

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#105]
but i moved it to be consistent with Graph-Explorer to:
http://shiny.neurodata.io/Vector-Explorer/

but i don't know how to re-route it.
thanks, j

**Comment by alexbaden** [comment]
Fixed. Had to update nginx config on dsp029.

**Comment by jovo** [comment]
love it.

On Mon, Jan 4, 2016 at 11:57 AM, Alex Baden notifications@github.com
wrote:

> Fixed. Had to update nginx config on dsp029.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/105#issuecomment-168733404
> .

## 

the glass is all full:  half water, half air.
neurodata.io
