### ISSUE TITLE
requesting admin access

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ocp.me#109]
@jovo — can @alexbaden and I grab admin access to this repo for deploy stuff?

**Comment by jovo** [comment]
granted.

On Wed, Feb 17, 2016 at 2:58 PM, Jordan Matelsky notifications@github.com
wrote:

> @jovo https://github.com/jovo — can @alexbaden
> https://github.com/alexbaden and I grab admin access to this repo for
> deploy stuff?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/neurodata.io/issues/109.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
#swag

thanks!
