### ISSUE TITLE
make the funding card smaller

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#14]
and maybe add logos?

**Comment by j6k4m8** [comment]
should i hunt down logos, or just leave it as it currently is?

**Comment by jovo** [comment]
leave.

On Fri, Aug 28, 2015 at 5:53 PM, Jordan Matelsky notifications@github.com
wrote:

> should i hunt down logos, or just leave it as it currently is?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/14#issuecomment-135896783
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York
