### ISSUE TITLE
if/when name is changed, note the following

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#16]
https://help.github.com/articles/renaming-an-organization/

which means that somebody else could create an openconnectome org,
and if they make new repos, they could overwrite our redirects

so, shortly after, we should create an 'openconnectome' org, 
with a comment that says our name changed, and a link

**Comment by jovo** [comment]
better yet, after making the new openconnectome organization,
we can make a new org page
(https://help.github.com/articles/user-organization-and-project-pages/)
which just points to our new page.

**Comment by jovo** [comment]
@j6k4m8 recommends just making neurodata a new org, forking, and the old ones will note that they are defunkt.

**Comment by wrgr** [comment]
won't people forget/have a hard time with this?

If I git pull github.com/openconnectome/cajal, I will never know
neurodata.io exists and is more up to date.

Best,
Will

On Thu, Aug 27, 2015 at 2:48 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i thought we'd say that it is depricated.
another option is to say that it is depricated, and delete all the content.
open to better suggestions.

On Thu, Aug 27, 2015 at 3:13 PM, William Gray notifications@github.com
wrote:

> won't people forget/have a hard time with this?
> 
> If I git pull github.com/openconnectome/cajal, I will never know
> neurodata.io exists and is more up to date.
> 
> Best,
> Will
> 
> On Thu, Aug 27, 2015 at 2:48 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > @j6k4m8 https://github.com/j6k4m8 recommends just making neurodata a
> > new org, forking, and the old ones will note that they are defunkt.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/16#issuecomment-135520202>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/16#issuecomment-135527050
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
i'd recommend deleting and changing readme to a link to the new page

**Comment by jovo** [comment]
"deleting" all content, but leaving repo, yes?

On Thu, Aug 27, 2015 at 4:55 PM, Jordan Matelsky notifications@github.com
wrote:

> i'd recommend deleting and changing readme to a link to the new page
> 
> On Thu, Aug 27, 2015 at 4:52 PM joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > i thought we'd say that it is depricated.
> > another option is to say that it is depricated, and delete all the
> > content.
> > open to better suggestions.
> > 
> > On Thu, Aug 27, 2015 at 3:13 PM, William Gray notifications@github.com
> > wrote:
> > 
> > > won't people forget/have a hard time with this?
> > > 
> > > If I git pull github.com/openconnectome/cajal, I will never know
> > > neurodata.io exists and is more up to date.
> > > 
> > > Best,
> > > Will
> > > 
> > > On Thu, Aug 27, 2015 at 2:48 PM, joshua vogelstein <
> > > notifications@github.com
> > > 
> > > > wrote:
> > > > 
> > > > @j6k4m8 https://github.com/j6k4m8 recommends just making
> > > > neurodata a
> > > > new org, forking, and the old ones will note that they are defunkt.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/16#issuecomment-135520202>
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/16#issuecomment-135527050>
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/16#issuecomment-135552275>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/16#issuecomment-135552738
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
Right -- so if you clone, you get a text file that's like NOPE

**Comment by wrgr** [comment]
NOPE.  WE HAVE DISABLED YOUR ACCESS TO DATA-DRIVEN NEUROSCIENCE.

Best,
Will
