### ISSUE TITLE
BigDataViewer link

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#21]
currently, link goes to their docs page.
@willgray i think maybe a box should appear, that explains how to use BigDataViewer to get OCP data, which i couldn't find on their site

**Comment by jovo** [comment]
we need to make a page (maybe sphinx) that explains how to use BigDataViewer with our stuff, because it is not documented anywhere

**Comment by wrgr** [comment]
I can be responsible for this.  In general, going forward, recommend that
authors of tools document tools to be included.  We are still in beta, so
makes sense this way, I think.

I might check with stephan and see if he has something somewhere.

Best,
Will

On Thu, Aug 27, 2015 at 2:46 PM, joshua vogelstein <notifications@github.com

**Comment by j6k4m8** [comment]
Should I wait on text for this?

**Comment by wrgr** [comment]
Yup. I sent a note requesting same.

**Comment by jovo** [comment]
i am closing this link.
@willgray create a github issue for me to check docs, maybe with a list that we can update so i can incrementally check them off as appropriate?
