### ISSUE TITLE
ready to go downloads

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#23]
why aren't AC3 and AC4 prepared downloads?

and kristen's annotated cube?

**Comment by j6k4m8** [comment]
They're in the works!

**Comment by j6k4m8** [comment]
@willgray I just finished compressing AC3 and AC4 (they're in `compressed/` in my dir on bg1) but I'm not sure where they're supposed to live...

**Comment by jovo** [comment]
@willgray - how about

/data/public/cutouts

as the place to keep all of them?

On Fri, Aug 21, 2015 at 5:33 PM, Jordan Matelsky notifications@github.com
wrote:

> @willgray https://github.com/willgray I just finished compressing AC3
> and AC4 (they're in compressed/ in my dir on bg1) but I'm not sure where
> they're supposed to live...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133569146
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
That's a fine idea.  We need to think about how we want to identify each
cutout in the raw cutout area.

Also, there's an argument that for small regions, we should be encouraging
the use of webform, cajal or ocpy.  No real benefit to cache
ac3/ac4/kristen's data?  Only for big stuff.  People lose all the metadata
this way, and it's also a problem because the projects get updated, and
regularly pulling to /data/public/cutouts is annoying.

@jordan - you pulled only the 100MB of raw data for AC4, not all of
kasthuri11, right?

Best,
Will

On Fri, Aug 21, 2015 at 5:41 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
ok, i don't have a strong opinion on how it works,
but i'd like people to be able to download AC3 and AC4 by clicking a button.

On Fri, Aug 21, 2015 at 6:16 PM, William Gray notifications@github.com
wrote:

> That's a fine idea. We need to think about how we want to identify each
> cutout in the raw cutout area.
> 
> Also, there's an argument that for small regions, we should be encouraging
> the use of webform, cajal or ocpy. No real benefit to cache
> ac3/ac4/kristen's data? Only for big stuff. People lose all the metadata
> this way, and it's also a problem because the projects get updated, and
> regularly pulling to /data/public/cutouts is annoying.
> 
> @jordan - you pulled only the 100MB of raw data for AC4, not all of
> kasthuri11, right?
> 
> Best,
> Will
> 
> On Fri, Aug 21, 2015 at 5:41 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > @willgray - how about
> > 
> > /data/public/cutouts
> > 
> > as the place to keep all of them?
> > 
> > On Fri, Aug 21, 2015 at 5:33 PM, Jordan Matelsky <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > @willgray https://github.com/willgray I just finished compressing
> > > AC3
> > > and AC4 (they're in compressed/ in my dir on bg1) but I'm not sure
> > > where
> > > they're supposed to live...
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133569146>
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133570368>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133578196
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
i have 1.8G of ac (per, not total), i believe

**Comment by wrgr** [comment]
We'll sort this out on Tuesday as part of our cajal/ocpy discussion?

Best,
Will

**Comment by j6k4m8** [comment]
sounds good to me

**Comment by jovo** [comment]
you are making a list?

On Fri, Aug 21, 2015 at 6:27 PM, William Gray notifications@github.com
wrote:

> We'll sort this out on Tuesday as part of our cajal/ocpy discussion?
> 
> Best,
> Will
> 
> On Fri, Aug 21, 2015 at 6:25 PM, Jordan Matelsky <notifications@github.com
> 
> 
> wrote:
> 
> > i have 1.8G of ac (per, not total), i believe
> > 
> > On Fri, Aug 21, 2015 at 6:22 PM joshua vogelstein <
> > notifications@github.com>
> > wrote:
> > 
> > > ok, i don't have a strong opinion on how it works,
> > > but i'd like people to be able to download AC3 and AC4 by clicking a
> > > button.
> > > 
> > > On Fri, Aug 21, 2015 at 6:16 PM, William Gray <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > That's a fine idea. We need to think about how we want to identify
> > > > each
> > > > cutout in the raw cutout area.
> > > > 
> > > > Also, there's an argument that for small regions, we should be
> > > > encouraging
> > > > the use of webform, cajal or ocpy. No real benefit to cache
> > > > ac3/ac4/kristen's data? Only for big stuff. People lose all the
> > > > metadata
> > > > this way, and it's also a problem because the projects get updated,
> > > > and
> > > > regularly pulling to /data/public/cutouts is annoying.
> > > > 
> > > > @jordan - you pulled only the 100MB of raw data for AC4, not all of
> > > > kasthuri11, right?
> > > > 
> > > > Best,
> > > > Will
> > > > 
> > > > On Fri, Aug 21, 2015 at 5:41 PM, joshua vogelstein <
> > > > notifications@github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > @willgray - how about
> > > > > 
> > > > > /data/public/cutouts
> > > > > 
> > > > > as the place to keep all of them?
> > > > > 
> > > > > On Fri, Aug 21, 2015 at 5:33 PM, Jordan Matelsky <
> > > > > notifications@github.com
> > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > @willgray https://github.com/willgray I just finished
> > > > > > compressing
> > > > > > AC3
> > > > > > and AC4 (they're in compressed/ in my dir on bg1) but I'm not
> > > > > > sure
> > > > > > where
> > > > > > they're supposed to live...
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133569146>
> > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > the glass is all full: half water, half air.
> > > > > openconnecto.me, jovo.me, office hours
> > > > > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133570368>
> > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133578196>
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > the glass is all full: half water, half air.
> > > openconnecto.me, jovo.me, office hours
> > > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > > —
> > > 
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133578833>
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133579387>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/23#issuecomment-133579703
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
