### ISSUE TITLE
LONI

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#26]
goes to our LONI sphinx docs

**Comment by j6k4m8** [comment]
http://openconnectome.github.io/ocpdocs/sphinx/loni.html ?

**Comment by jovo** [comment]
yup,  still a stub, @willgray will migrate content from
http://w.ocp.me/tools:loni
or will delegate :)

On Fri, Aug 21, 2015 at 5:36 PM, Jordan Matelsky notifications@github.com
wrote:

> http://openconnectome.github.io/ocpdocs/sphinx/loni.html ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/26#issuecomment-133569609
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
@gkiar - can you help with this?  Probably need screenshots and/or a rewrite.  Part of  ocpdocs sphinx, which has no imports or code to autodoc
