### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#29]
maybe just a box pop's up with two options:
- OCP forum
- Contact us

**Comment by j6k4m8** [comment]
this is now all in the footer. still want a popup?

**Comment by jovo** [comment]
no

On Fri, Aug 28, 2015 at 6:09 PM, Jordan Matelsky notifications@github.com
wrote:

> this is now all in the footer. still want a popup?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/29#issuecomment-135899270
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York
