### ISSUE TITLE
Visualize

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#35]
the boxes (CATMAID, OCPVIZ, and BIGDATAVIEWER) bottoms aren't aligned with the bottom of the card, i don't want white space _below_ the boxes though.

**Comment by j6k4m8** [comment]
Card shortened appropriately. [code](https://github.com/openconnectome/ocp.me/blob/master/client/templates/home/_visualize.html#L5)

**Comment by jovo** [comment]
are these `done` issues "pushed"?

**Comment by jovo** [comment]
@j6k4m8 maybe don't worry about this until we decide whether to add 
- Graph Explore, and
- Gephi 

here, cuz if so, this gets re-arranged a bit

**Comment by j6k4m8** [comment]
worrying has been later'd. let me know when to re-worry this

in the meantime: the done tag means on-the-server-ready-for-your-perusal.
Just realized this one didn't push, i just re-added it and it'll be in the
next release.
