### ISSUE TITLE
Visualize

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#37]
- remove "Visit our visualization page for more information."
  no need for 'viz' page
- add Graph Explore
- maybe add a link to Gephi for local graph viz?

@willgray thoughts?

**Comment by wrgr** [comment]
Agree!

**Comment by j6k4m8** [comment]
gephi link plz?

**Comment by wrgr** [comment]
http://gephi.github.io/

Best,
Will

**Comment by jovo** [comment]
this is dead based on our convo yesterday.
