### ISSUE TITLE
info page doesn't have the navbar

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#38]

**Comment by j6k4m8** [comment]
The navbar links are local links to items on the homepage... so i nix'd them for sites that weren't the homepage. We can add different links to each page, or I can permalink to the homepage from there?

**Comment by jovo** [comment]
i see.
well, for the info page, i think the homepage navbar makes sense?
but if you think otherwise, i trust you.

On Fri, Aug 21, 2015 at 4:27 PM, Jordan Matelsky notifications@github.com
wrote:

> The navbar links are local links to items on the homepage... so i nix'd
> them for sites that weren't the homepage. We can add different links to
> each page, or I can permalink to the homepage from there?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/38#issuecomment-133551033
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
Homepage navbar seems reasonable to me — I'll add it in the next roll.
