### ISSUE TITLE
icon is the old favicon, should be the new one

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#39]

**Comment by j6k4m8** [comment]
where does the new favicon live?

**Comment by jovo** [comment]
usually all that stuff lives here:
https://drive.google.com/open?id=0By_9m7n8XhYKfmJFNTdwUnQ5ZUtpT29rVU12Y1ZCS2sxMEhERXhaMFh4NUFySTlQbFpVYjQ

On Fri, Aug 21, 2015 at 5:34 PM, Jordan Matelsky notifications@github.com
wrote:

> where does the new favicon live?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/39#issuecomment-133569379
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
it may take some time for your cache to clear and the browser to see the new favicon

**Comment by jovo** [comment]
still is the old one for me
