### ISSUE TITLE
sphinx pages all not working because of redirects to mri.ocp.me

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp.me#40]
Relatively high priority because this breaks all access to our documentation.

Full paths:  openconnectome.github.io/<repo> fails too...

**Comment by jovo** [comment]
who can fix this?

On Thu, Aug 20, 2015 at 9:45 PM, William Gray notifications@github.com
wrote:

> Relatively high priority because this breaks all access to our
> documentation.
> 
> Full paths: openconnectome.github.io/ fails too...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
Not sure.  @alexbaden maybe knows?

I'm super unclear what is happening right now with redirects and:

ocp.me
openconnecto.me
openconnectomeproject.org

My hope is there is just a rewrite rule for openconnectome.github.io ->
mri.ocp.me somewhere and we can just remove it and at least the full doc
paths will work again.

Best,
Will

On Thu, Aug 20, 2015 at 9:46 PM, joshua vogelstein <notifications@github.com

**Comment by alexbaden** [comment]
That's a jordan thing. I just checked dsp029 and there's no mention of
ocp.me anywhere. So, the mri.ocp.me A record probably got changed, and
that's why gh-pages are broken. I'm not sure how you guys set that up in
the first place, so I'm not sure how to fix it.

On another note, we should probably all meet in person before changing
openconnecto.me at all. Our current system is based on hosting the public
site at openconnectomeproject.org and using openconnecto.me for all of our
services (ocp, catmaid, viz, data hosting, etc). We forwad the
openconnecto.me/index.html page to openconnectomeproject.org. It is
possible to work something else out, we just need to do it carefully to
avoid breaking literally hundreds of catmaid links.

Alex

**Comment by jovo** [comment]
@alexbaden - good call.  when are you back?

On Thu, Aug 20, 2015 at 11:17 PM, Alex Baden notifications@github.com
wrote:

> That's a jordan thing. I just checked dsp029 and there's no mention of
> ocp.me anywhere. So, the mri.ocp.me A record probably got changed, and
> that's why gh-pages are broken. I'm not sure how you guys set that up in
> the first place, so I'm not sure how to fix it.
> 
> On another note, we should probably all meet in person before changing
> openconnecto.me at all. Our current system is based on hosting the public
> site at openconnectomeproject.org and using openconnecto.me for all of our
> services (ocp, catmaid, viz, data hosting, etc). We forwad the
> openconnecto.me/index.html page to openconnectomeproject.org. It is
> possible to work something else out, we just need to do it carefully to
> avoid breaking literally hundreds of catmaid links.
> 
> Alex
> 
> On Thu, Aug 20, 2015 at 6:49 PM William Gray notifications@github.com
> wrote:
> 
> > Not sure. @alexbaden maybe knows?
> > 
> > I'm super unclear what is happening right now with redirects and:
> > 
> > ocp.me
> > openconnecto.me
> > openconnectomeproject.org
> > 
> > My hope is there is just a rewrite rule for openconnectome.github.io ->
> > mri.ocp.me somewhere and we can just remove it and at least the full doc
> > paths will work again.
> > 
> > Best,
> > Will
> > 
> > On Thu, Aug 20, 2015 at 9:46 PM, joshua vogelstein <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > who can fix this?
> > > 
> > > On Thu, Aug 20, 2015 at 9:45 PM, William Gray <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Relatively high priority because this breaks all access to our
> > > > documentation.
> > > > 
> > > > Full paths: openconnectome.github.io/ fails too...
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/openconnectome/ocp.me/issues/40.
> > > 
> > > ## 
> > > 
> > > the glass is all full: half water, half air.
> > > openconnecto.me, jovo.me, office hours
> > > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133243212>
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133244176>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133263857
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by alexbaden** [comment]
Tuesday night. On campus Weds - October. :-)

**Comment by jovo** [comment]
ok, let's all meet wed at noon, lunch on me if somebody buys,
and we'll roll to new website?

@willgray @kunallillaney @j6k4m8 @alexbaden - can you all be here for that?

**Comment by wrgr** [comment]
Giving a talk on images to graphs at APL at noon.  Can we do sometime
Tuesday?  Early/late ok by me.

**Comment by jovo** [comment]
@alexbaden - can you do tues night?

On Thu, Aug 20, 2015 at 11:54 PM, William Gray notifications@github.com
wrote:

> Giving a talk on images to graphs at APL at noon. Can we do sometime
> Tuesday? Early/late ok by me.
> 
> On Thu, Aug 20, 2015 at 11:51 PM joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > ok, let's all meet wed at noon, lunch on me if somebody buys,
> > and we'll roll to new website?
> > 
> > @willgray https://github.com/willgray @kunallillaney
> > https://github.com/kunallillaney @j6k4m8 https://github.com/j6k4m8
> > @alexbaden https://github.com/alexbaden - can you all be here for
> > that?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133272209>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133272393
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by alexbaden** [comment]
My flight lands at 10pm. :-(

**Comment by jovo** [comment]
@willgray ok, wed afternoon after your talk or thursday?

**Comment by kunallillaney** [comment]
I can do anytime Tuesday,Wednesday or Thursday.

**Comment by jovo** [comment]
@all - friday then?

On Fri, Aug 21, 2015 at 12:01 AM, Kunal Lillaney notifications@github.com
wrote:

> I can do anytime Tuesday,Wednesday or Thursday.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133273185
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by kunallillaney** [comment]
@jovo Why not Thursday?

**Comment by jovo** [comment]
@kunallillaney cuz i can't read :-1: 

@willgray wed afternoon or thurs?

**Comment by j6k4m8** [comment]
This is resolved, correct? e.g. http://openconnectome.github.io/macho/index.html works (though mri.ocp.me/macho -- perhaps rightfully -- no longer works)

**Comment by jovo** [comment]
do we want all of our docs to live at things like

 http://openconnectome.github.io/macho/index.html

or do we prefer

http://<ournewsitename>/macho/index

?

On Fri, Aug 21, 2015 at 5:24 PM, Jordan Matelsky notifications@github.com
wrote:

> This is resolved, correct? e.g.
> http://openconnectome.github.io/macho/index.html works (though
> mri.ocp.me/macho -- perhaps rightfully -- no longer works)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133566923
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
Hmm...the index autoresolves, so just:
http://openconnectome.github.io/macho

Adding redirects once we have them is a fine idea - I think it's
conceptually and practically great to host pages on the gh-pages address;
that is, the openconnectome.github.io... link is the real hosting location.

Best,
Will

On Fri, Aug 21, 2015 at 5:40 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
ok, you decide best practice and let's do that.

On Fri, Aug 21, 2015 at 6:14 PM, William Gray notifications@github.com
wrote:

> Hmm...the index autoresolves, so just:
> http://openconnectome.github.io/macho
> 
> Adding redirects once we have them is a fine idea - I think it's
> conceptually and practically great to host pages on the gh-pages address;
> that is, the openconnectome.github.io... link is the real hosting location.
> 
> Best,
> Will
> 
> On Fri, Aug 21, 2015 at 5:40 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > do we want all of our docs to live at things like
> > 
> > http://openconnectome.github.io/macho/index.html
> > 
> > or do we prefer
> > 
> > http://<ournewsitename>/macho/index
> > 
> > ?
> > 
> > On Fri, Aug 21, 2015 at 5:24 PM, Jordan Matelsky <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > This is resolved, correct? e.g.
> > > http://openconnectome.github.io/macho/index.html works (though
> > > mri.ocp.me/macho -- perhaps rightfully -- no longer works)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133566923>
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133570186>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133577859
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
Ok.  Each sphinx site should be hosted on gh-pages

We should add redirects for each tool, so that we have:  ocp.me/<tool>
that points to the gh-pages site (with masking if available.)

Best,
Will

On Fri, Aug 21, 2015 at 6:21 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
@willgray - ok, claim or delegate :)

On Fri, Aug 21, 2015 at 6:49 PM, William Gray notifications@github.com
wrote:

> Ok. Each sphinx site should be hosted on gh-pages
> 
> We should add redirects for each tool, so that we have: ocp.me/<tool>
> that points to the gh-pages site (with masking if available.)
> 
> Best,
> Will
> 
> On Fri, Aug 21, 2015 at 6:21 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > ok, you decide best practice and let's do that.
> > 
> > On Fri, Aug 21, 2015 at 6:14 PM, William Gray notifications@github.com
> > wrote:
> > 
> > > Hmm...the index autoresolves, so just:
> > > http://openconnectome.github.io/macho
> > > 
> > > Adding redirects once we have them is a fine idea - I think it's
> > > conceptually and practically great to host pages on the gh-pages
> > > address;
> > > that is, the openconnectome.github.io... link is the real hosting
> > > location.
> > > 
> > > Best,
> > > Will
> > > 
> > > On Fri, Aug 21, 2015 at 5:40 PM, joshua vogelstein <
> > > notifications@github.com
> > > 
> > > > wrote:
> > > > 
> > > > do we want all of our docs to live at things like
> > > > 
> > > > http://openconnectome.github.io/macho/index.html
> > > > 
> > > > or do we prefer
> > > > 
> > > > http://<ournewsitename>/macho/index
> > > > 
> > > > ?
> > > > 
> > > > On Fri, Aug 21, 2015 at 5:24 PM, Jordan Matelsky <
> > > > notifications@github.com
> > > > 
> > > > > wrote:
> > > > > 
> > > > > This is resolved, correct? e.g.
> > > > > http://openconnectome.github.io/macho/index.html works (though
> > > > > mri.ocp.me/macho -- perhaps rightfully -- no longer works)
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133566923>
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > the glass is all full: half water, half air.
> > > > openconnecto.me, jovo.me, office hours
> > > > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133570186>
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133577859>
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133578722>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133582350
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
Yah - this is currently assigned to @j6k4m8.  I think that's right.  We need redirects for each of the boxes on the cards under analyze that points to a sphinx site.  I think Jordan is the guy for redirects.  If not, then @j6k4m8 should assign as appropriate.  Sites all exist in their gh-pages location, currently.

**Comment by j6k4m8** [comment]
this is going to be a client-side-level redirect if it's done through the
meteor app (which is probably best for the sake of maintainability)...
which is to say that the URL bar will change to the github.io page. That ok?

**Comment by jovo** [comment]
i support whatever works, certainly for now.

On Fri, Aug 21, 2015 at 7:21 PM, Jordan Matelsky notifications@github.com
wrote:

> this is going to be a client-side-level redirect if it's done through the
> meteor app (which is probably best for the sake of maintainability)...
> which is to say that the URL bar will change to the github.io page. That
> ok?
> 
> On Fri, Aug 21, 2015 at 6:54 PM William Gray notifications@github.com
> wrote:
> 
> > Yah - this is currently assigned to @j6k4m8 https://github.com/j6k4m8.
> > I think that's right. We need redirects for each of the boxes on the
> > cards
> > under analyze that points to a sphinx site. I think Jordan is the guy for
> > redirects. If not, then @j6k4m8 https://github.com/j6k4m8 should
> > assign
> > as appropriate. Sites all exist in their gh-pages location, currently.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133582872>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/40#issuecomment-133588102
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
Great!
