### ISSUE TITLE
Video section

### ISSUE THREAD

**Issue by ebridge2** [openconnectome/ocp.me#42]
Have a section for everybody to upload a one or two minute video introducing themself, their interests, hobbies, etc along with a short intro on their research work

**Comment by j6k4m8** [comment]
this seems like a #8 sort of question...

**Comment by wrgr** [comment]
Enumerate what you need and I'll help? I can probably tell you most of what
you are missing.

**Comment by j6k4m8** [comment]
Mostly just want to punt on this one until the team page is A Thing...
sounds like a lot of work for pre-SfN
