### ISSUE TITLE
top scrolling on new pages

### ISSUE THREAD

**Issue by gkiar** [openconnectome/ocp.me#45]
going from the main page to, say, http://www.ocp.me/info, the browser doesn't scroll back up so if you were down the page you'll see the bottom of the info page when it loads. perhaps an easy-ish way to reset the scrollbar on link click exists?

**Comment by j6k4m8** [comment]
hrm. interesting.

**Comment by j6k4m8** [comment]
ignoring this for now... i know what's causing it and it's going to be a pain to fix...
