### ISSUE TITLE
Add data to MeganDB

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp.me#5]
Megan to provide a restful endpoint or webpage to put data in MeganDB

**Comment by j6k4m8** [comment]
until we implement authorization, this needs to be done manually from the commandline (to prevent people "updating" projects that are not theirs). I'm happy to do this, I just need access to wherever it lives. 

@alexbaden if you're cool with this living on brainapps I can probably handle it

**Comment by j6k4m8** [comment]
https://github.com/openconnectome/ocpmeta/issues/1
