### ISSUE TITLE
migrate LONI info from w.ocp.me to ocp.me

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#51]
@gkiar feel free to delegate :)

**Comment by jovo** [comment]
@willgray is this done?

**Comment by wrgr** [comment]
nope - owed from @gkiar - if that's not good, we can reevaluate

**Comment by gkiar** [comment]
Forgot I owned this. Sorry about that. Do we want it somewhere on
neurodata.io or actually on http://docs.neurodata.io/nddocs/ ?

## 

Greg Kiar gkiar07@gmail.com

**Comment by wrgr** [comment]
Not yet done.   I think nddocs.  Just make a new md page?

**Comment by jovo** [comment]
i put a bunch of issues into 1 bigger issue,
i fear that the list was so long it scared people
maybe a bad idea
just experimenting...

On Sun, Sep 27, 2015 at 1:53 PM, William Gray notifications@github.com
wrote:

> Not yet done. I think nddocs. Just make a new md page?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/51#issuecomment-143580820
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York
