### ISSUE TITLE
maybe visualize should have 4 boxes too

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#53]
|  | Web | Local |
| --- | --- | --- |
| images |  |  |
| graphs |  |  |

@willgray @j6k4m8 what do you guys think?

**Comment by wrgr** [comment]
consistency is important - no reason to make people learn things a bunch of times.  so i like parallel layouts between visualize, exchange, analyze...

![ocptools - what does ocp do- 2](https://cloud.githubusercontent.com/assets/884780/9426082/f0708bbe-48f7-11e5-9ae5-80be283a934f.png)

**Comment by jovo** [comment]
i support web & local for viz & upload & download.

analyze also gets cluster (ie, analytics framework).

"A foolish consistency is the hobgoblin of small minds."

**Comment by wrgr** [comment]
roger that.  I find lots of quotes in favor of consistency, but hard to
compete with emerson.
