### ISSUE TITLE
make everything lowercase

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#55]
(maybe not the navbar, TBD).  discuss?

**Comment by j6k4m8** [comment]
define everything. text, or just titles?

**Comment by jovo** [comment]
i think i mean everything.
like, no caps anywhere.

On Thu, Aug 27, 2015 at 2:10 PM, Jordan Matelsky notifications@github.com
wrote:

> define everything. text, or just titles?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/55#issuecomment-135510256
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York
