### ISSUE TITLE
if its not too hard, make scrolling cover up old sections (like on the JHU site)

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#57]

**Comment by j6k4m8** [comment]
will do, but takes a few hours to fine-tune and make it compat' with old browsers... probably a project for post-launch, unless it's higher priority>

**Comment by jovo** [comment]
definitely post launch.

On Thu, Aug 27, 2015 at 1:20 PM, Jordan Matelsky notifications@github.com
wrote:

> will do, but takes a few hours to fine-tune and make it compat' with old
> browsers... probably a project for post-launch, unless it's higher priority>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/57#issuecomment-135497555
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York
