### ISSUE TITLE
neurodata.io doesn't load in my office

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#72]
https://www.dropbox.com/s/vhb5r1sa37hnmx5/Screenshot%202015-08-27%2017.06.32.png?dl=0

maybe a hopkins networking thing.
probably effects other jhu computers.

@alexbaden

**Comment by alexbaden** [comment]
Perhaps a DNS resolution issue?

abaden@ambp:~$ ping neurodata.io

PING neurodata.io (50.63.202.58): 56 data bytes

I would think it should have the IP 128.220.176.7 .

**Comment by jovo** [comment]
PING neurodata.io (128.220.176.7): 56 data bytes

Request timeout for icmp_seq 0

Request timeout for icmp_seq 1

On Thu, Aug 27, 2015 at 5:13 PM, Alex Baden notifications@github.com
wrote:

> Perhaps a DNS resolution issue?
> 
> abaden@ambp:~$ ping neurodata.io
> 
> PING neurodata.io (50.63.202.58): 56 data bytes
> 
> I would think it should have the IP 128.220.176.7 .
> 
> On Thu, Aug 27, 2015 at 5:08 PM joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > https://www.dropbox.com/s/vhb5r1sa37hnmx5/Screenshot%202015-08-27%2017.06.32.png?dl=0
> > 
> > maybe a hopkins networking thing.
> > probably effects other jhu computers.
> > 
> > @alexbaden https://github.com/alexbaden
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openconnectome/ocp.me/issues/72.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/72#issuecomment-135556442
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York

**Comment by alexbaden** [comment]
But ocp.me works? Possibly an issue in the nginx config...
s/possibly/probably/ :-)

Alex

**Comment by jovo** [comment]
ocp.me works.

On Thu, Aug 27, 2015 at 5:18 PM, Alex Baden notifications@github.com
wrote:

> But ocp.me works? Possibly an issue in the nginx config...
> s/possibly/probably/ :-)
> 
> Alex
> 
> On Thu, Aug 27, 2015 at 5:17 PM joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > PING neurodata.io (128.220.176.7): 56 data bytes
> > 
> > Request timeout for icmp_seq 0
> > 
> > Request timeout for icmp_seq 1
> > 
> > On Thu, Aug 27, 2015 at 5:13 PM, Alex Baden notifications@github.com
> > wrote:
> > 
> > > Perhaps a DNS resolution issue?
> > > 
> > > abaden@ambp:~$ ping neurodata.io
> > > 
> > > PING neurodata.io (50.63.202.58): 56 data bytes
> > > 
> > > I would think it should have the IP 128.220.176.7 .
> > > 
> > > On Thu, Aug 27, 2015 at 5:08 PM joshua vogelstein <
> > > notifications@github.com>
> > > wrote:
> > > 
> > 
> > https://www.dropbox.com/s/vhb5r1sa37hnmx5/Screenshot%202015-08-27%2017.06.32.png?dl=0
> > 
> > > > maybe a hopkins networking thing.
> > > > probably effects other jhu computers.
> > > > 
> > > > @alexbaden https://github.com/alexbaden
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/openconnectome/ocp.me/issues/72.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/ocp.me/issues/72#issuecomment-135556442>
> > 
> > > .
> > 
> > ## 
> > 
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> > 
> > https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/ocp.me/issues/72#issuecomment-135557030>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/72#issuecomment-135557286
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
i accuse hopkins dns

**Comment by wrgr** [comment]
at home.  not vpn'ed.  doesn't work.   :)

Best,
Will

**Comment by alexbaden** [comment]
I think I fixed it. Give it an hour and try again.

**Comment by j6k4m8** [comment]
alex's changes should be DNS-propagated by now, if this is still an issue, let me know

**Comment by ronboger** [comment]
yeah can't access it either on the DMC computers

**Comment by j6k4m8** [comment]
not sure what to tell you, aside from spam the clear-cache button in chrome
and pray that your DNS clears _its_ cache in the near future... can you
ping?

**Comment by ronboger** [comment]
100% packet loss on ping

**Comment by alexbaden** [comment]
Can you do an nslookup?

**Comment by jovo** [comment]
still doesn't work @alexbaden 

Last login: Thu Aug 20 09:23:43 on ttys000
metatron:~ jovo$ ping neurodata.io
PING neurodata.io (128.220.176.7): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
Request timeout for icmp_seq 11
Request timeout for icmp_seq 12
Request timeout for icmp_seq 13
Request timeout for icmp_seq 14
Request timeout for icmp_seq 15
Request timeout for icmp_seq 16
Request timeout for icmp_seq 17
Request timeout for icmp_seq 18
Request timeout for icmp_seq 19
Request timeout for icmp_seq 20
Request timeout for icmp_seq 21
Request timeout for icmp_seq 22
Request timeout for icmp_seq 23
Request timeout for icmp_seq 24
Request timeout for icmp_seq 25
Request timeout for icmp_seq 26
Request timeout for icmp_seq 27
Request timeout for icmp_seq 28
Request timeout for icmp_seq 29
Request timeout for icmp_seq 30
Request timeout for icmp_seq 31
Request timeout for icmp_seq 32
Request timeout for icmp_seq 33
Request timeout for icmp_seq 34
Request timeout for icmp_seq 35
Request timeout for icmp_seq 36
Request timeout for icmp_seq 37
Request timeout for icmp_seq 38
Request timeout for icmp_seq 39
Request timeout for icmp_seq 40
^C
--- neurodata.io ping statistics ---
42 packets transmitted, 0 packets received, 100.0% packet loss
metatron:~ jovo$ nslookup neurodata.io
Server:     192.168.1.15
Address:    192.168.1.15#53

Non-authoritative answer:
Name:   neurodata.io
Address: 128.220.176.7

metatron:~ jovo$

**Comment by wrgr** [comment]
works for me!  at home.

Best,
Will

On Mon, Aug 31, 2015 at 3:26 PM, joshua vogelstein <notifications@github.com

**Comment by alexbaden** [comment]
Pretty sure this is a JHU firewall / network routing issue. I reached out
to our guy there. Right now, neurodata.io should work on JHU wifi and
outside of JHU, but not on JHU wired connections. Please correct me if I'm
wrong so I can pass the right info to networking.

**Comment by j6k4m8** [comment]
I think we decided this was a Hopkins firewall issue?

i.e. wired connections on campus = not good

**Comment by j6k4m8** [comment]
Ah, Alex beat me to it...

**Comment by alexbaden** [comment]
Fixed.
