### ISSUE TITLE
Main Page for all neurodata documentation

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ocp.me#74]
- https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
- docs.neurodata.io

@alexbaden @willgray @jovo

**Comment by jovo** [comment]
docs.neurodata.io doesn't work for me.

On Fri, Aug 28, 2015 at 5:56 PM, Jordan Matelsky notifications@github.com
wrote:

>    -
>    https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
> - docs.neurodata.io
> 
> @alexbaden https://github.com/alexbaden @willgray
> https://github.com/willgray @jovo https://github.com/jovo
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp.me/issues/74.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York
