### ISSUE TITLE
make postdoc ad

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#76]
"Neurodata invites outstanding candidates to apply for a postdoctoral or assistant research scientist position in the area of statistical machine learning for big brain imaging data. Our workflow is tightly vertically integrated, ranging from raw data analysis to statistical theory to answering neuroscience questions and back again. Along the way, we develop new scalable methods (ideally with provable properties), and we apply previously developed methods in novel contexts. All of our projects include machine learning and big statistics, and integrate computer vision, systems engineering, numerical algorithms, and parallel computing. In short, we use/develop whatever technologies are necessary to answer today's most important, open, and long-standing questions in neuroscience.  To apply, please send jovo@jhu.edu an email including: (i) a curriculum vita, and (ii) the names and email addresses of three references. "

ideally, put banner at the top, linking to a page with this content, much like the one currently on cis.jhu.edu

**Comment by jovo** [comment]
[postdoc.pdf](https://github.com/openconnectome/neurodata.io/files/7260/postdoc.pdf)

please put a link to this pdf in a bar at the top of the page?

**Comment by j6k4m8** [comment]
"John Hopkins U" ^ in the pdf

**Comment by j6k4m8** [comment]
otherwise, ad is there, neurodata.io/hiring will exist in a few seconds.
