### ISSUE TITLE
do we want to install a jupyter docker on brainapps?

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#77]
https://hub.docker.com/r/jupyter/jupyterhub/

might make sharing analyses with each other and others way easier?

@j6k4m8 @willgray @alexbaden @gkiar have any comments?

**Comment by j6k4m8** [comment]
I'm very on board. Dont know what's involved logistically but it seems like
a smart move, even if just for internal use.

Though I can see mooc using it as well, plus it's an awesome way of
documenting common user stories

**Comment by j6k4m8** [comment]
@alexbaden do you mind if i do this? if that's cool with you, give me an ip/port combo that i can use and i'll set it up
