### ISSUE TITLE
docs configuration

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp.me#78]
All, 

How should we organize our docs?  We have a bunch of sphinx sites:

openconnectome
ocptilecache
m2g.io
i2g.io
cajal
macho
manno

etc.

I like the idea of using ocpdocs -> neurodatadocs -> docs? as a main landing page for users (docs.neurodata.io?), with links everywhere.  Might be nice to have some other pages directly linked as well.

@j6k4m8 @jovo @kunallillaney @alexbaden @gkiar

**Comment by kunallillaney** [comment]
+1

**Comment by jovo** [comment]
+1.

I vote org within that is like the websige/mooc

**Comment by wrgr** [comment]
Great!  So then, can we forward docs.neurodata.io to
openconnectome.github.io/docs ?

I feel like it's a CNAME thing.  Jordan kept telling me what to do, but I
got...redirected.  (ha!)

Help?

docs.neurodata.io should go to the openconnectome.github.io/docs site
openconnectome.github.io/vesicle (and others) should still resolve to their
own sites if at all possible, when typed directly.  (Maybe that doesn't
work with slashes and gh-page websites?)
