### ISSUE TITLE
OCPeeps

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#8]
for each person, i'd like:
- image
- their 'publication name' (eg, Joshua T. Vogelstein)
- role (will should know)
- button links to their stuff, eg, personal web page, github page, linked in page, etc.

**Comment by jovo** [comment]
also include alumni

jacob
dean
priya
eric
ayushi

**Comment by j6k4m8** [comment]
I'm working on this behind the scenes, FYI. Once I have photos/words for everyone, I'll push :)
- [x] jovo
- [x] will
- [x] jordan
- [x] @randalburns
- [x] @kunallillaney 
- [x] @gkiar
- [ ] da
- [ ] kwame
- [x] disa
- [x] ayushi
- [ ] @Aeusman 
- [ ] cep

### alum
- [x] brother
- [ ] dean
- [ ] priya
- [ ] eric

Non-exhaustive, feel free to edit but I'll use the wiki peeps site as my master list, this for checklist.
put in alphabetical order
can push now, will update over time.
