### ISSUE TITLE
add modalities text

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ocp.me#82]
add AT text [here](https://github.com/openconnectome/neurodata.io/blob/master/client/templates/modalities/at/home.html#L9), EM [here](https://github.com/openconnectome/neurodata.io/blob/master/client/templates/modalities/em/home.html#L9), [clarity](https://github.com/openconnectome/neurodata.io/blob/master/client/templates/modalities/clarity/home.html#L9), and [this](https://github.com/openconnectome/neurodata.io/blob/master/client/templates/modalities/mri/home.html#L9) is where MRI lives, but it's already written.

Each also has a 'coming soon' which we can either replace or delete.

**Comment by jovo** [comment]
- EM coming soon should be replaced with the list of EM projects
- AT doesn't have a coming soon, just the 1 project, which is right
- CLARITY should still have a coming soon
- MRI doesn't have a coming soon.

i updated all the main text paragraphs, and hopefully didn't break anything else.

@j6k4m8 fixes coming soon's, and then this one is done.

**Comment by j6k4m8** [comment]
https://github.com/openconnectome/neurodata.io/blob/master/client/templates/modalities/calcium/home.html#L10

@jovo
