### ISSUE TITLE
needs to be done by wed 9AM

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#83]
- [x] "Access" is called "Browse"
- [x] make sure all projects links work (they don't now)
- [x] all modalities pages need content (@jovo action)
- [x] visualize/exchange "bar" changes as discussed, ie, 3 cards, each with 2 buttons, one called "images" and one called "graphs"
  - visualize - images links to http://openconnecto.me/catmaid/, graphs links to ge.neurodata.io
  - upload  - link to image upload page, add warning in text of page that it is still in development mode, for graphs, just say "coming soon"
  - download - image download page obviously, and then http://openconnecto.me/graph-services/download/ for graphs
- [x] Analyze, under code, just have "neuroimages" and "neurographs"
- [x] make sure funding lists all grants in the attached file
  [NSF_Vogelstein_currentpend_2015_Sep.docx](https://github.com/openconnectome/neurodata.io/files/3148/NSF_Vogelstein_currentpend_2015_Sep.docx)
- [x] "enabling data-driven neuroscience at scale"
- [x] change "images" to "neuroimages" and graphs to "neurographs" everywhere

**Comment by jovo** [comment]
videos that would be awesome to convert to gifs, 
(googling yielded several seemingly adequate tools):
and be cycling instead of that somewhat creepy picture of a head
(note that credit must be given on each, possibly the easiest way would be to just list credits at the bottom of the page?)

### Array Tomography videos (pick one)
- [ ] https://www.youtube.com/watch?v=WRhfuFOU2sg
- [ ] https://www.youtube.com/watch?v=ebwd5baIQXY

### CLARITY
- [ ] https://www.youtube.com/watch?v=c-NMfp13Uug (around the 2 min mark is good)

### Electron Microscopy
- [ ] https://www.youtube.com/watch?v=5Lc64j-Rsy4 (around 2:13)

### Diffusion MRI
- [ ] https://www.youtube.com/watch?v=_oTEhFAAARE (around 2:30)

### Calcium Imaging
- [ ] https://www.youtube.com/watch?v=lppAwkek6DI

**Comment by wrgr** [comment]
For EM, stuff from the cell paper directly (supplementary videos) - might
be simpler to convert.  I think that basically these are just different
versions of the same thing, but without the post-production/embedding.

**Comment by j6k4m8** [comment]
access _should_ be called browse, or is but shouldn't? (that is, change it to access or change it to browse?)

**Comment by j6k4m8** [comment]
and what info from each of the attached grants should i include..? sorry, just not sure what the correct protocol is for listing these, they don't have the same sort of serial numbers we already list

**Comment by jovo** [comment]
change access to browse. sorry for confusion.

On Tue, Sep 29, 2015 at 12:02 PM, Jordan Matelsky notifications@github.com
wrote:

> access _should_ be called browse, or is but shouldn't? (that is, change
> it to access or change it to browse?)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/83#issuecomment-144103977
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by jovo** [comment]
just gave you new funding direction

On Tue, Sep 29, 2015 at 12:11 PM, joshua vogelstein jovo@jhu.edu wrote:

> change access to browse. sorry for confusion.
> 
> On Tue, Sep 29, 2015 at 12:02 PM, Jordan Matelsky <
> notifications@github.com> wrote:
> 
> > access _should_ be called browse, or is but shouldn't? (that is, change
> > it to access or change it to browse?)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openconnectome/neurodata.io/issues/83#issuecomment-144103977
> > .
> 
> ## 
> 
> the glass is all full:  half water, half air.
> openconnecto.me, medhacks http://medhacks.org/, calendar
> https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by jovo** [comment]
@willgray i think for @j6k4m8 to finish this nddocs needs to have at least the top level structure (code & web-services)

**Comment by wrgr** [comment]
Confused - is the google doc the same as what you sent before?  I figured
out markdown and sphinx and have a local working copy.  Should I just push?

**Comment by jovo** [comment]
oh, yes, please push
