### ISSUE TITLE
a bunch of minor things

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#84]
- [x] finish main page for all neurodata docs @willgray 
- [x] link to console from 'upload/ingest' page @j6k4m8 
- [x] change access to browse and 'brain' to 'neuro' @j6k4m8 
- [x] change 'info' to 'about' @j6k4m8 
- [x] install jupyter docker on brainapps @j6k4m8 
- [ ] navbar consistent across all pages, highlights (eg bold) the submenu we are on @j6k4m8 
- [x] migrate everything from HSSL & w.ocp.me to docs (is this done already) @kunallillaney @Aeusman 
- [x] references should link to mendeley groups (https://www.mendeley.com/groups/1680241/neurodata-publications/papers/) @j6k4m8 
- [x] add card called links linking to the old links page @j6k4m8 
- [ ] move HSSL to brainapps @alexbaden

**Comment by j6k4m8** [comment]
removed swag link task, excised to #89 so we can close this without waiting on making links for swag.

**Comment by kunallillaney** [comment]
A link to the token creation console.

**Comment by jovo** [comment]
@alexbaden what is the status on moving HSSL to brainapps?
i'm closing this issue. feel free to open again.
