### ISSUE TITLE
funding should be organized as follows

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#85]
all info listed below, organized as follows.
sometimes there is no grant #.
note that i need all this info for my cv, 
so i'd like in the future to easily be able to add new info here,
and also my cv.
not sure that matters, but thought i'd put that out there.
### any public document (talk, poster, paper)

\cventry{5/15 -- 5/18}{From Rags to Riches: Utilizing Richly Attributed Graphs}{N66001-15-C-4041}{DARPA (SIMPLEX)}{Vogelstein (PI)}{}
### light microscopy / cell detection

\cventry{3/13 -- 1/16}{Computational infrastructure for massive neuroscience image stacks}{NIH/NSF (BIGDATA)}{1R01DA036400}{Mitra (PI)}{}
### MRI

\cventry{7-15 -- 6/17}{Quantifying Individual Differences in Network Dynamics for Abstract Information Learning}{}{Science of Learning Institute}{Courtney (PI)}{}

\cventry{2/13 -- 9/15}{Endeavor Scientists Training Fellowship}{}{Child Mind Institute}{Vogelstein (PI)}{}
### calcium imaging

\cventry{7-15 -- 6/17}{Learning Causes Changes in the State-Space of Local Cortical Networks}{}{Science of Learning Institute}{Nielsen (PI)}{}
### array tomography

\cventry{9/14 -- 6/19}{Synaptomes of Mouse and Man}{NIH (TRA)}{R01 OD19123}{Smith (PI)}{}
### graphs

\cventry{5/14 -- 2/16}{Scalable Brain Graph Analyses Using Big-Memory, High-IOPS Compute Architectures}{DARPA (GRAPHS)}{DARPA-BAA-13-15}{Burns (PI)}{}

\cventry{10/12 -- 3/17}{Fusion and Inference from Multiple and Massive Infrastructure for Massive Neuroscience}{DARPA (XDATA)}{FA8750-12-2-0303}{Priebe (PI)}{}

NSF ACI-1261715,
NSF OCI-1040114,
### past funding

JHU Applied Research Laboratory IRAD,
JHU Whiting School of Engineering Dean's Award.

\cventry{9/12 -- 8/15}{Data Sharing: The EM Open Connectome Project}{NIH/NIBIB (CRCNS)}{1R01EB016411}{Burns (PI)}{}

\cventry{1/14 -- 12/14}{Data Readiness Level}{Laboratory for Analytic Sciences}{}{Harer (PI)}{}

\cventry{1/12 -- 10/13}{Graph-Based Scalable Analytics for Big Data}{DARPA (XDATA)}{FA8750-12-C-0239}{Andrews (PI)}{}

\cventry{12/09 -- 1/13}{National Center for Applied Neuroscience Project}{NSF}{}{RJ Vogelstein (PI)}{}

**Comment by j6k4m8** [comment]
let's talk at some point about clever ways of syncing up CV and HTML. I never found any good way of mixing LaTeX and HTML, and eventually settled for [html alone](http://jordan.matelsky.com/resume/) (judge thee not the poor state of my neurodata entry; i've been busy...)

I wrote a setup that auto-PDFs my resume whenever there's a change ([PDF](http://jordan.matelsky.com/resume/Jordan-Matelsky-Resume.pdf)) and it looks different than the HTML, but not necessarily bad...

**Comment by j6k4m8** [comment]
html also lets you do cool stuff like [this](http://jordan.matelsky.com/resume/#beta) (click and drag in the grey to change specificity (y axis) and topic <med-tech> (x-axis))

**Comment by j6k4m8** [comment]
should be [resolved](http://neurodata.io/about)

**Comment by jovo** [comment]
hmm...interesting....i'm curious to learn how you did that.
the html page is weird, i can't select things and such....

On Tue, Sep 29, 2015 at 9:19 PM, Jordan Matelsky notifications@github.com
wrote:

> should be resolved http://neurodata.io/about
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/85#issuecomment-144247015
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, medhacks http://medhacks.org/, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
^ by design. 

well, actually more by "i wonder how to disable selection" than by design
