### ISSUE TITLE
more stuff that would be great to be done soon

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#86]
- [x] navbar should say: {Browse, Capabilites, About}
- [x] remove "Analyze existing...."
- [x] under web-services:
  - "Open-Connectome" should read "Neuroimage Services" and should link to appropriate place in nddocs
  - "MRI Graph Services" --> "mri2graphs"
  - mri2graphs should be the bottom, not the 2nd one.
- [x] bottom bar
  - [x] support links to support forum (@gkiar can provide link?)
  - [x] remove newsletter for now, will link to blog.neurodata.io once we set it up
  - [x] contact is pop-up to "support@neurodata.io"
  - [x] make it transparent or black or something
- [x] remove "Bock DD..." from references, only need that one link for now.
- [x] navbar should have "browse" "capabilities" and "about"

**Comment by j6k4m8** [comment]
the contact-form popup means we need an SMTP server...or a mailgun setup or something. but no matter what, it's probably going to change once we have someone else writing our code.

**Comment by jovo** [comment]
they can post on the support forum, no need to email us.
