### ISSUE TITLE
fix word cloud background and circle

### ISSUE THREAD

**Issue by gkiar** [openconnectome/ocp.me#87]
& make people page find-able (i.e. no link to it currently exists)

![neuropeep](https://cloud.githubusercontent.com/assets/4883288/10324878/2c461eca-6c5b-11e5-9735-1dcf6d609c61.png)

**Comment by j6k4m8** [comment]
no link currently exists because i don't have pictures for everyone... help would be lovely, but otherwise we can just push this!

**Comment by jovo** [comment]
Skip pics. Let's just push with word cloud.

**Comment by jovo** [comment]
@j6k4m8 i did it!
but there is a dumb white background and circle that i don't know how to take away :(
