### ISSUE TITLE
bottom bar

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#9]
- copyright
- "contact us" button which links to email or forum
- sign up for newsletter button
- twitter "button"
- facebook "button"

**Comment by j6k4m8** [comment]
We have a newsletter?

**Comment by jovo** [comment]
We will!

**Comment by j6k4m8** [comment]
@gkiar can you PR a link to the newsletter? or give me a signup link and I'll add?

**Comment by gkiar** [comment]
https://groups.google.com/a/neurodata.io/d/forum/announce

is where the newsletter lives. You want me to PR it to a button or is this
ok?

## 

Greg Kiar gkiar07@gmail.com

**Comment by j6k4m8** [comment]
perff. pushing it now.
