### ISSUE TITLE
Add a small list of all the supported tools

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/ocp.me#92]
@jovo We should have a list of all the supported tools - VAST, BigDataViewer, Ilastik, VIKING, KNOSSOS, and more. Sort of say that if you fell comfortable using any of the tools above then you can still use the data stored here.

**Comment by jovo** [comment]
i believe @willgray claimed this?

**Comment by jovo** [comment]
this is elsewhere now. i suck at gihub, so i won't link to it, though i should.
