### ISSUE TITLE
tiny webpage stuff

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#93]
- [x] "Visualize", "Upload" and "Download" look the same as "Code" (in particular, gray bar in "header"
- [x] update footer:
  - [x] make twitter button really a twitter icon, and remove the word "twitter"
  - [x] add link to facebook 
  - [x] add link to blog (with blogger favicon?)
  - [x] add link to swag (with customink logo)
- [x] link to pdf in postdoc ad goes to the wrong pdf, it goes to the one with "John" hopkins, rather than "Johns"

**Comment by gkiar** [comment]
customink doesn't allow you to link your design for anyone to purchase. The
pens were ordered internally. The stickers is the same as customink - the
design is private.

## 

Greg Kiar gkiar07@gmail.com

On Wed, Oct 14, 2015 at 1:28 PM, joshua vogelstein <notifications@github.com

**Comment by j6k4m8** [comment]
^that's re #89

**Comment by gkiar** [comment]
ah, yes, there is a small button in this one too though :)

## 

Greg Kiar gkiar07@gmail.com

**Comment by jovo** [comment]
@gkiar custom-ink says you can share the design, and they will send a link to a specified email address.  then, we can use that link to share with anybody we want, and they can buy it if they want

**Comment by gkiar** [comment]
The purchase would be a group order through us, though. I don't want to be
in the loop.

**Comment by jovo** [comment]
they disagree.  send me credentials to log in, i'll check into it.

**Comment by jovo** [comment]
@gkiar link?

**Comment by gkiar** [comment]
http://www.customink.com/designs/neurodata/nxa0-00ab-4tvx/social?cm_cat=google&cm_ite=neurodata&cm_pla=share&cm_ven=social

## 

Greg Kiar gkiar07@gmail.com

On Thu, Oct 22, 2015 at 7:34 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
@j6k4m8 please spend the next 10 minutes that you are working on neurodata stuff working on this issue.  thank you.

**Comment by j6k4m8** [comment]
will do — the only real time-consuming one is DLing AC3/4. @willgray do you know if we have these on bg1?

**Comment by jovo** [comment]
i'm fairly sure they are there. or somewhere else like that

On Sun, Nov 8, 2015 at 12:36 AM, Jordan Matelsky notifications@github.com
wrote:

> will do — the only real time-consuming one is DLing AC3/4. @willgray
> https://github.com/willgray do you know if we have these on bg1?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/93#issuecomment-154776798
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by wrgr** [comment]
I have them. What format? Or do you just want tokens and bounds? Let's
enumerate data samples to share with one click and which format we prefer?

**Comment by jovo** [comment]
1. in terms of which data samples to share, i trust your judgement, so long as it includes AC3 & AC4.
2. in terms of how to deliver them, i'd say a zip file contain a png or tiff stack, also containing a readme with a link to the jupyter notebook that scripts downloading the cutout including RAMON objects? i realize this step might be more time consuming that just putting up another tiff stack, so i'm open to punting on this for the moment.

**Comment by wrgr** [comment]
1.  ok
2.  More confusing - in that raw data from the server generally won't come
   as tiff/png files, but wrapped in HDF5 and converted downstream.  We can do
   either/both - I think what you want is a zip file and a jupyter notebook
   that at least corresponds to the data (if not the format) for each zip
   file.  If we do this, I need help knowing where we should put all of these
   jupyter files...it's maybe annoying to keep 10+ of these files up to
   date...not sure.

I can figure something out if no one has strong opinions, but thought I'd
ask first.

Best,
Will

On Sun, Nov 8, 2015 at 12:45 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
Do 1.
We can discuss 2 later..

**Comment by jovo** [comment]
ps - its 1 jupyter notebook, where the user specifies which of the several
ready made cutouts he/she wants, and in which format, and it does
everything.  this should not be overly burdensome to support.  let's make a
git issue specifically to create this notebook, and we'll get to it at some
point (maybe hackathon, maybe later).

On Tue, Nov 10, 2015 at 6:10 PM, William Gray notifications@github.com
wrote:

> 1. ok
> 2. More confusing - in that raw data from the server generally won't come
>    as tiff/png files, but wrapped in HDF5 and converted downstream. We can do
>    either/both - I think what you want is a zip file and a jupyter notebook
>    that at least corresponds to the data (if not the format) for each zip
>    file. If we do this, I need help knowing where we should put all of these
>    jupyter files...it's maybe annoying to keep 10+ of these files up to
>    date...not sure.
> 
> I can figure something out if no one has strong opinions, but thought I'd
> ask first.
> 
> Best,
> Will
> 
> On Sun, Nov 8, 2015 at 12:45 PM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > 1.
> > 
> > in terms of which data samples to share, i trust your judgement, so
> > long as it includes AC3 & AC4.
> > 2.
> > 
> > in terms of how to deliver them, i'd say a zip file contain a png or
> > tiff stack, also containing a readme with a link to the jupyter notebook
> > that scripts downloading the cutout including RAMON objects? i realize
> > this
> > step might be more time consuming that just putting up another tiff
> > stack,
> > so i'm open to punting on this for the moment.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/neurodata.io/issues/93#issuecomment-154852474
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/93#issuecomment-155597102
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
pulling the ready-to-go's into their own issue, closing this with your approval!

**Comment by j6k4m8** [comment]
![image](https://cloud.githubusercontent.com/assets/693511/11182559/a9ec0d3c-8c39-11e5-897d-0e972cc2c50b.png)

![image](https://cloud.githubusercontent.com/assets/693511/11182562/ae67da08-8c39-11e5-9cc2-08cddbff74fb.png)

![image](https://cloud.githubusercontent.com/assets/693511/11182570/b4b99bda-8c39-11e5-9099-64da04ccb780.png)
