### ISSUE TITLE
why is the repo 660 MB?

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#97]
seems....unnecessary?
no need to fix, i'm just curious.

**Comment by j6k4m8** [comment]
we push a site-ready version of the repo through git so that it's a one-liner to set up on the server. definitely not necessary, but hasn't been a priority to fix in light of other bigger issues. Will eventually resolve, I promise!

**Comment by jovo** [comment]
i don't mind, i was just curious, because their is not that much content.
