### ISSUE TITLE
fix ico

### ISSUE THREAD

**Issue by ronboger** [openconnectome/ocp.me#98]
current ico isn't transparent, making note for myself to fix

**Comment by ronboger** [comment]
@jovo can you add me as a contributor so i can push the fix?

**Comment by jovo** [comment]
pull request and i'll merge.

On Mon, Nov 16, 2015 at 11:47 AM, ron boger notifications@github.com
wrote:

> @jovo https://github.com/jovo can you add me as a contributor so i can
> push the fix?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/neurodata.io/issues/98#issuecomment-157093954
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment]
does this exist?

**Comment by ronboger** [comment]
yes... my bad i didn't see jovos comment. the better ico is used for jovo.me,
i'll PR later today

On Mon, Nov 16, 2015 at 2:22 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i did it.
