### ISSUE TITLE
"ready to go" should include AC3 & AC4

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ocp.me#99]
@willgray halp

**Comment by wrgr** [comment]
@j6k4m8 - should I just send you coordinates?  Or a tar file?

**Comment by wrgr** [comment]
I think this is sufficient - I just don't know how you want to save the volumes and where to post them.  @j6k4m8  - resolve or tell me how?

ac4_image = oo.get_cutout('kasthuri11cc', 'image', 4400, 5424, 5440, 6464, 1100, 1200, resolution=1)

ac4_synapses = oo.get_cutout('ac3ac4', 'ac4_synapse_truth', 4400, 5424, 5440, 6464, 1100, 1200, resolution=1)

ac4_neurons = oo.get_cutout('ac3ac4', 'ac4_neuron_truth', 4400, 5424, 5440, 6464, 1100, 1200, resolution=1)

ac3_image = oo.get_cutout('kasthuri11cc', 'image', 5472, 6496, 8712, 9736, 1000, 1256, resolution=1)
